[package]
name = "freeswitch-sofia-trace-torture"
version = "0.1.0"
edition = "2021"
license = "GPL-3.0-only"
publish = false

[dependencies]
freeswitch-sofia-trace-parser = { path = ".." }
rayon = "1"

[dev-dependencies]
eido = { git = "https://gitlab.cauca.ca/cauca-public/eido", features = ["xml"] }
sip-header = "1.0.0-beta.2"
